CREATE TABLE IF NOT EXISTS reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    tmp_from DATETIME DEFAULT CURRENT_TIMESTAMP,
    tmp_to DATETIME DEFAULT CURRENT_TIMESTAMP,
    send BOOLEAN,
    name TEXT,
    message TEXT
);

CREATE TABLE IF NOT EXISTS logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    source TEXT,
    code TEXT,
    message TEXT
);

CREATE TABLE IF NOT EXISTS logs_error (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    source TEXT,
    code TEXT,
    message TEXT
);

CREATE TABLE IF NOT EXISTS logs_trace (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    source TEXT,
    code TEXT,
    message TEXT
);

CREATE TABLE IF NOT EXISTS logs_warning (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    source TEXT,
    code TEXT,
    message TEXT
);